[build]
builder = "dockerfile"
dockerfile = "backend/Dockerfile.railway"

[deploy]
startCommand = "bash /app/start-railway.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 