# Generated by Django 5.2.3 on 2025-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Only update race_type choices - this is safe and won't conflict
        migrations.AlterField(
            model_name='callout',
            name='race_type',
            field=models.CharField(
                choices=[
                    ('quarter_mile', 'Quarter Mile'),
                    ('eighth_mile', 'Eighth Mile'),
                    ('roll_race', 'Roll Race'),
                    ('dig_race', 'Dig Race'),
                    ('heads_up', 'Heads Up'),
                    ('bracket', 'Bracket Racing')
                ],
                help_text='Type of race',
                max_length=50
            ),
        ),
    ] 