# Generated by Django 4.2.10 on 2025-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link_url', models.URLField(max_length=500)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_location', models.CharField(help_text="e.g., 'homepage', 'marketplace', 'event_list'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Whether event is sponsored'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_logo_url',
            field=models.URLField(blank=True, help_text='Sponsor logo URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='Sponsor name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_website_url',
            field=models.URLField(blank=True, help_text='Sponsor website URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe product ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for marketplace sellers', max_length=255, null=True),
        ),
    ]
