# Generated by Django 4.2.10 on 2025-07-06 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_stripe_connect_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], help_text='Type of OTP (phone or email)', max_length=10)),
                ('identifier', models.CharField(help_text='Phone number or email address', max_length=255)),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'code', 'is_used'], name='core_otp_identif_21718b_idx'), models.Index(fields=['expires_at'], name='core_otp_expires_288351_idx')],
            },
        ),
    ]
