# Generated by Django 5.2.3 on 2025-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_callout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callout',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('pro', 'Pro')], default='intermediate', help_text='Required experience level', max_length=20),
        ),
        migrations.AddField(
            model_name='callout',
            name='is_invite_only',
            field=models.BooleanField(default=False, help_text='Whether callout requires invitation approval'),
        ),
        migrations.AddField(
            model_name='callout',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Whether callout is private (only visible to participants)'),
        ),
        migrations.AddField(
            model_name='callout',
            name='max_horsepower',
            field=models.IntegerField(blank=True, help_text='Maximum horsepower requirement', null=True),
        ),
        migrations.AddField(
            model_name='callout',
            name='min_horsepower',
            field=models.IntegerField(blank=True, help_text='Minimum horsepower requirement', null=True),
        ),
        migrations.AddField(
            model_name='callout',
            name='rules',
            field=models.TextField(blank=True, help_text='Special rules or conditions for the race'),
        ),
        migrations.AddField(
            model_name='callout',
            name='tire_requirement',
            field=models.CharField(blank=True, help_text='Tire requirements for the race', max_length=200),
        ),
    ]
