# Generated by Django 5.2.3 on 2025-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_callout_experience_level_callout_is_invite_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, help_text='Token for email verification', null=True, unique=True),
        ),
    ]
