# Generated by Django 5.2.3 on 2025-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_email_verification_token_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(null=True, blank=True, unique=True, help_text='Token for email verification'),
        ),
    ]
