# Generated by Django 5.2.3 on 2025-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_email_verification_token_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Backup codes for OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False, help_text='Whether OTP is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_expires_at',
            field=models.DateTimeField(blank=True, help_text='When password reset token expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, help_text='When password reset email was sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, help_text='Token for password reset', null=True, unique=True),
        ),
    ]
