# Generated by Django 5.2.3 on 2025-07-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_remaining_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Whether this is a live stream'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='live_stream_title',
            field=models.CharField(blank=True, help_text='Live stream title', max_length=200),
        ),
        migrations.AddField(
            model_name='userpost',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='Live stream URL', null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='live_viewers_count',
            field=models.IntegerField(default=0, help_text='Number of live viewers'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('video', 'Video Post'), ('race_result', 'Race Result'), ('car_update', 'Car Update'), ('live', 'Live Stream')], default='text', help_text='Type of post', max_length=20),
        ),
    ]
