# Generated by Django 5.2.3 on 2025-07-07 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_live_streaming_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='announcement_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the announcement', max_length=20),
        ),
        migrations.AddField(
            model_name='userpost',
            name='announcement_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('feature', 'New Feature'), ('maintenance', 'Maintenance'), ('promotion', 'Promotion'), ('event', 'Event')], help_text='Type of announcement', max_length=50),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_challenged_user',
            field=models.ForeignKey(blank=True, help_text='User being challenged in the callout', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_post_callouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_location',
            field=models.CharField(blank=True, help_text='Race location (street or dragstrip)', max_length=500),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_location_type',
            field=models.CharField(blank=True, choices=[('street', 'Street Race'), ('dragstrip', 'Dragstrip Race')], help_text='Type of race location', max_length=20),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_race_type',
            field=models.CharField(blank=True, help_text='Type of race (sprint, circuit, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date for the race', null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the callout', max_length=20),
        ),
        migrations.AddField(
            model_name='userpost',
            name='callout_wager_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wager amount for the race', max_digits=10),
        ),
        migrations.AddField(
            model_name='userpost',
            name='is_announcement',
            field=models.BooleanField(default=False, help_text='Whether this is a system announcement'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether this announcement is pinned'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='is_race_callout',
            field=models.BooleanField(default=False, help_text='Whether this is a race callout'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('video', 'Video Post'), ('race_result', 'Race Result'), ('car_update', 'Car Update'), ('live', 'Live Stream'), ('race_callout', 'Race Callout'), ('announcement', 'Announcement')], default='text', help_text='Type of post', max_length=20),
        ),
    ]
