# Generated by Django 5.2.3 on 2025-06-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_callout_options_alter_friendship_options_and_more'),
    ]

    operations = [
        # This migration is intentionally empty to handle deployment issues
        # where tables may already exist in the production database
    ]
