# Generated by Django 5.2.3 on 2025-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpost_announcement_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification')], default='login', help_text='Purpose of the OTP', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose'], name='core_otp_purpose_b49549_idx'),
        ),
    ]
