# Generated by Django 4.2.10 on 2025-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_otp_with_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredcontent',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
