# Generated by Django 4.2.10 on 2025-06-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listingcategory_marketplacelisting_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When member joined'),
        ),
        migrations.AlterField(
            model_name='crewmembership',
            name='member',
            field=models.ForeignKey(help_text='Crew member', on_delete=django.db.models.deletion.CASCADE, related_name='crew_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='racingcrew',
            name='owner',
            field=models.ForeignKey(help_text='Crew owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_crews', to=settings.AUTH_USER_MODEL),
        ),
    ]
