# Generated by Django 4.2.10 on 2025-07-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_crewmembership_joined_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
